type Query {
    currentUser: User,
    postsByUser(userId: String!): [Post]
}

type User {
    id: ID!
    username: String!
    posts: [Post]
}

type Post {
    id: ID!
    content: String!
    userID: ID!
}